# file is outdated and not reflective of my codebase at all
name: Cypress E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run tests daily at 8 AM UTC
    - cron: '0 8 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, edge]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          headed: false
          spec: cypress/e2e/menu.spec.js
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      
      - name: Generate report
        if: always()
        run: |
          npm run report:merge
          npm run report:generate
      
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots
          retention-days: 7
      
      - name: Upload test report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report-${{ matrix.browser }}
          path: cypress/reports
          retention-days: 30
      
      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const reportPath = 'cypress/reports/report.json';
            if (fs.existsSync(reportPath)) {
              const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));
              const { passes, failures, pending, duration } = report.stats;
              const status = failures > 0 ? ' Failed' : 'Passed';
              
              const comment = `
              ## Cypress Test Results ${status}
              
              | Metric | Value |
              |--------|-------|
              | Passed | ${passes} |
              | Failed | ${failures} |
              | Skipped | ${pending} |
              | Duration | ${(duration / 1000).toFixed(2)}s |
              
              Browser: ${{ matrix.browser }}
              `;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }